# Generated by Django 6.0 on 2026-01-11 13:00

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('spec', models.CharField(blank=True, default='', max_length=300)),
                ('unit', models.CharField(blank=True, default='', max_length=20)),
                ('material_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('labor_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('expense_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TakeoffLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('line_tag', models.CharField(db_index=True, max_length=120)),
                ('work_type', models.CharField(db_index=True, max_length=80)),
                ('code', models.CharField(db_index=True, max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('spec', models.CharField(blank=True, default='', max_length=300)),
                ('unit', models.CharField(blank=True, default='', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rate_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='progress.rateitem')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_done', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.progressperiod')),
                ('takeoff_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.takeoffline')),
            ],
            options={
                'unique_together': {('period', 'takeoff_line')},
            },
        ),
    ]
