# Generated by Django 6.0 on 2026-01-11 15:41

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_ratecodemap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('total_units', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UnitSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField()),
                ('line_no', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('UNIT', '세대'), ('BLOCKED', '제외(X)'), ('FACILITY', '부대시설'), ('BASEMENT', '지하')], default='UNIT', max_length=10)),
                ('label', models.CharField(blank=True, default='', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('tower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='progress.tower')),
                ('unit_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='progress.unittype')),
            ],
            options={
                'unique_together': {('tower', 'floor', 'line_no')},
            },
        ),
        migrations.CreateModel(
            name='TypeRateUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_per_unit', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('rate_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.rateitem')),
                ('unit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.unittype')),
            ],
            options={
                'unique_together': {('unit_type', 'rate_item')},
            },
        ),
        migrations.CreateModel(
            name='UsageEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_qty', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('used_qty', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.progressperiod')),
                ('rate_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.rateitem')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.unitslot')),
            ],
            options={
                'unique_together': {('period', 'slot', 'rate_item')},
            },
        ),
    ]
